##########################################
# Site Settings
staticDir = ['static']
baseURL = "https://yz7043.github.io/andyzhu/"
title = "Andy Zhu's Blog"

theme = "m10c"
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  #[[menu.main]]
  #  identifier = "tags"
  #  name = "Tags"
  #  url = "/tags/"
  #  weight = 2
  [[menu.main]]
    identifier = "posts"
    name = "Post"
    url = "/posts/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "Andy Zhu"
  description = "Welcome to my tech blogs!"
  menu_item_separator = " - "
  avatar = "https://drive.google.com/uc?export=view&id=1L37pCrrw-QBS23cfrO-cvqwo4F9LHcRl"
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/yz7043"
  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/yuxiangzhu57/"

  # Default theme
  #[params.style]
  #  darkestColor = "#242930"
  #  darkColor = "#353b43"
  #  lightColor = "#afbac4"
  #  lightestColor = "#ffffff"
  #  primaryColor = "#57cc8a"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
  #  primaryColor = "#dad865"

  # Red theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  lightColor = "#d6d6d6"
  #  lightestColor = "#d3d3d3"
  #  primaryColor = "#ffffff"
